# Generated by Django 4.1.7 on 2023-03-31 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='', max_length=50)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.field')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('singleSelect', 'singleSelect')], default='text', max_length=20)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.form')),
            ],
            bases=('app.field',),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('select_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.selectfield')),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.field')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('regex', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('regexErrorMessage', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.form')),
            ],
            bases=('app.field',),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('select_field', 'value'), name='unique_value_per_fk'),
        ),
    ]
