# Generated by Django 4.1.7 on 2023-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='value',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
