# Generated by Django 4.1.7 on 2023-03-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inputfield_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfield',
            name='value',
        ),
    ]
