# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_inputfield_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='regex',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='regexErrorMessage',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selectfield',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
